# Instance name set on Wolf and shown by Moonlight client
wolf_instance_name: wolf

# Image versions to use for each apps
# Lock version with hash for better reproducibility
wolf_server_image: ghcr.io/games-on-whales/wolf:stable@sha256:5bf5041065dbfea67e60c3a28a42a551be970feed5d1be6d59bee2d134da1770
wolf_app_steam_image: ghcr.io/games-on-whales/steam:edge@sha256:e1bc09a265fe2ee95499efc8c7431c1cccfd8b1c99553aa5bf32305ec8ce482a
wolf_app_lutris_image: ghcr.io/games-on-whales/lutris:edge@sha256:7f96dd7c990d13d62a87d08969cb756ee1418f0690af6dbe15125e6acd4c679a
wolf_app_pegasus_image: ghcr.io/games-on-whales/pegasus:edge@sha256:0a30ce11257219b0a8630339fe0b75ccea9462d7a7d58f65218de68b4409e09a
wolf_app_retroarch_image: ghcr.io/games-on-whales/retroarch:edge@sha256:0da32e530583040b917268b7f96245fcbf9744ec7ce03619fdec2f90fcc4fe1e
wolf_app_prismlauncher_image: ghcr.io/games-on-whales/prismlauncher:edge@sha256:e8f4451ec81946a54f886b36d4cf99c38878a452fe442351320631441024d303
wolf_app_firefox_image: ghcr.io/games-on-whales/firefox:edge@sha256:097eb6a311fe6b5c60dfdd6b8f5e6e32f4bcd1cca9eaf2b1ea46afe5f06a4da8

# Directory where Wolf project config is stored (eg. Docker Compose files)
wolf_project_dir: "{{ ansible_user_dir }}/wolf"

# Where Wolf container data are stored
wolf_data_dir: "/var/lib/cloudypad/wolf"

wolf_legacy_data_dir: "/etc/wolf"

# Whether to pull app images in parallel for faster subsequent startup when using Wolf
# Disabled by default to avoid pulling images when not needed
wolf_app_preheat_images_pull: false