roles:
  - name: geerlingguy.docker
    version: "7.4.5"
collections:
  - name: https://github.com/ansible-collections/community.docker.git
    type: git
    version: "4.3.1"
  - name: https://github.com/ansible-collections/community.general.git
    type: git
    version: "10.3.0"
  - name: https://github.com/ansible-collections/ansible.posix.git
    type: git
    version: "2.0.0"