roles:
  - name: geerlingguy.docker
    version: "7.4.5"
collections:
  - name: community.docker
    version: "4.3.1"
  - name: community.general
    version: "10.3.0"
  - name: ansible.posix
    version: "2.0.0"