[book]
authors = ["Pierre Beucher"]
language = "en"
multilingual = false
src = "src"
title = "Cloudy Pad ğŸ® ğŸŒ¥ï¸"
description = "Cloudy Pad: deploy your own gaming gear in the Cloud !"

[output.html]
git-repository-url = "https://github.com/PierreBeucher/cloudypad"
edit-url-template = "https://github.com/PierreBeucher/cloudypad/edit/master/docs/{path}"