galaxy_info:
  author: Pierre Beucher
  description: Wolf is an open source streaming server for Moonlight that allows you to share a single server with multiple remote clients in order to play videogames!

  license: GNU GPLv3

  min_ansible_version: "2.10"

  galaxy_tags: []

dependencies: []